{% set name = "polyline" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyline-{{ version }}.tar.gz
  sha256: 1492b8fcadc2143f8aedc673d3c6d95df45131f1c62eb8d51c8183b24e771486

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - polyline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/polyline/
  summary: A Python implementation of Google's Encoded Polyline Algorithm Format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
