{% set version = "1.4.0" %}

package:
  name: polyline
  version: {{ version }}

source:
  fn: polyline-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/polyline/polyline-{{ version }}.tar.gz
  md5: b97c57378605c4a856c437569f95a0cb

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - six >=1.8.0

test:
  imports:
    - polyline

about:
  home: https://github.com/hicsail/polyline
  license: MIT
  license_file: LICENSE
  summary: "A Python implementation of Google's Encoded Polyline Algorithm Format."

extra:
  recipe-maintainers:
    - ocefpaf
