{% set version = "2.0.0" %}

package:
  name: polyline
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/polyline/polyline-{{ version }}.tar.gz
  sha256: 1492b8fcadc2143f8aedc673d3c6d95df45131f1c62eb8d51c8183b24e771486

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.8.0

test:
  imports:
    - polyline

about:
  home: https://github.com/hicsail/polyline
  license: MIT
  license_file: LICENSE
  summary: A Python implementation of Google's Encoded Polyline Algorithm Format

extra:
  recipe-maintainers:
    - ocefpaf
