travis:
  secure:
    BINSTAR_TOKEN: jMTPwtyfk9zgH1LljmP3tD5/CQZwSfhYq6c2j9wKgAj5w0wvRB1Ak7D4sX9taORb6w3+6tBSOvDm6GwE2VyLLkJjLu+hMDNcn6uPjVZfsa2CR+OjDhmojypAHOumzw3KPgx/YxgPGGLP5ZtKibWhGPW+yqjegtgxmR8QFkrvPRR0KL0Ylj7ITXfk6ZhRQBZSPQzj/uEwgKMlW/giy8XRmMZp1JFrXLdbtqU6PXbAHpR5asEBxXI2ra4AMGnSJt0SRbM7LpcvgFXCaSBDA18rzLX3fvh4ByFN/yrkk1bMuFwtxWjj/HxrszkmANVnh66S5xqalH/1yrSD9hzQMtcMiBb/Bun2SUO8XmXDmoXQLO866TwhSPuTxvWOSmX3X6OnK6gOEHGm9P3oRjugazAR/HYOFTXWblHqB4JvbzRVQbR6bblZYbo4KBEy2OOtV36pSe5G0ntd1Qwl0yjpul0lK8kDSuIuFv+TiReiOUex5O5Ouv1w0COpdggCVVB/KJ9icaBLj0orWmVO3uDll6A1wuOzxhGw9qbLEhN7znG/Y2UoZuQPKGceXx4QWaAKA5Q6gBsJLhQ0+I0lMbMO4zffZGYLiqZ02kUIKoHlk7nHIIIkekhAn7fguCehQG6zSoIxWK7vQCYe8rQ/xqHlXDlICYPODf+8IebznCxKkYfU9Ao=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
