travis:
  secure:
    BINSTAR_TOKEN: ScIHvPdVDOAefJ62n2GrGOhkGe/tbRLM7QvtBQ0I55PUIODW6nfxOEheRbaAVplro4DriKq21M/E7226SyZC+FE/bNOFLfrTuxH3IFKm5DG0cLwrVAC8qhpSJZy5JDoFHYEuc5D4meMROzRoOFero4qywTWHYZX/P8tqKeYO1SeaRcT4sABhOKZbEOwMYDx/7lwN/vPCkE9k/vkmLSQwLXaUaFUsl70Q79GOXYRJPCiD5TCESOU99z+wtTtNPEvqUi3eLYw3SH+G62y7jHlRfzrY2Z9FTPA5azuDTLfsH+0tH5c6F843H4jhlxQpss4s0An++v0wLOqH5UdeIlhltqre+7KAHWmwh3ZGJAmiSD2wSWs2bmWP6IavSkHpmujnPSCq3+5t0bRYsoyM0TDlt1uApq8ItdC1k2wOT8qVA6Acw2mwb3ODGkqVyIh+pwLfF2md3szwlvoW5MseKdsY/J/bVJPySwnwzOaUe9oyKEBRSG2DaHgfwQUv2Hb/fWVT+V2BmBHwL5xRIQj93NJ5wTaZmjN7UyAsWVNU1WrdPmyZEntEEJOgOF8DjevcY7cPL+d4FcSFePBTyF+Aps0Kbi1CfyIte7amzL7d+DCbtUJebmUQ6nS0ShB9WIeBYewLgEDWJ6/bcpFswXHmRunexvs1QoXw3iCU5goG5UHo3nM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
