travis:
  secure:
    BINSTAR_TOKEN: ofiwMbDBG5AToAUmehE5zB8+9PAwnL5hJ7aTSkTLUfgDBcYb+8LP0KNdyzeGFeSDi8KKBLrYUZZKRNX3M9XQ//+AirGC5u9EAElkz9JE7vKSFxzVnhoOGzBByZEhxnOxrZnrSzWQxEn/rUThDIg54Nsvubm5A5rcPB5hDhnvyiD+O2g6pXkb1JrR+8KLG2U16+SIKw2NOfELf52tl183tZNb5YUF3ann6BqganwmUO36q2GfdDJm2fHxjUSVQU/HsUkLE5tdKaFonmsxP8bsxJkBCV2vlKD8uzEK6gyxyimx1FpFiLvYsAy7lYuMOoe49DgQD5AW3n9/ghR+PomUZsBUTQOKZQVVdka1ZfTAaRfuXlND46j8MMOPqNlM1DYKmLnlNU1mnSBf5LlxjpIs7TUCaUnaqH4ZvrivabZprDbYjexEpuAs2K8XTQrO90iqmbuPNTUedaCvOISFnHwrBgCoja1RMTVKygGCOE8wkjOVTY4MrUqDkDVPtlhVDdeHXG3LRvQ3drwyXr+gNHM6Xl67oeEql6xUV/sXf9SpjfoPso8GVPr67QouizKIkRMjEsQgWGW7mhxswvgJUOgIfvdRvWSYC1AlaFgDorHMIi41Nnb3Ld8SN2uM23aqFgiSZMxvD03AAFXxpKi+S4Gq0kCpOrFn1PtAzXXRWeAshoo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
